### ISSUE TITLE
Why not use Laravel's ValidationException?

### ISSUE THREAD

**Issue by mattzuba** [AltThree/Validator#11]
Laravel's Exception handler has built in handling for Illuminate `ValidationException`s, but that doesn't work with the ValidationException thrown in this package without overriding that method in the exception handler.  Any reason why Laravel's wouldn't be used instead?

**Comment by GrahamCampbell** [comment]
I guess because that exception doesn't exist in L5.1?

**Comment by ItsiAdam** [comment]
Since this package doesn't support L5.1 now, could this be reconsidered?

**Comment by GrahamCampbell** [comment]
The reason we aren't going to use it is because it has an http response on it, and this package was intended to not know about HTTP.
